// Renders the insights aggregate into LESSONS.md — the repo's static teaching
// artifact, readable on GitHub without running anything. Pure: string in/out.

export const GLOSSARY = [
  {
    term: 'One-shot',
    def: 'A self-contained project an AI coding tool builds from a single written vision. "One-shot" as an outcome means it worked from one prompt, with no human corrections.',
  },
  {
    term: 'Token',
    def: 'The unit AI models read and write text in (roughly ¾ of a word). Build tokens measure how much work — and money — a build consumed.',
  },
  {
    term: 'Fidelity',
    def: 'A human score (0–100%) of how closely the built result matches the written vision.',
  },
  {
    term: 'Evidence level',
    def: "Where a measurement came from. Only machine-observed sources (the tool's own session records or provider usage exports) are trusted — the model is never asked to report its own numbers.",
  },
  {
    term: 'Benchmark-eligible',
    def: 'An attempt whose token/time telemetry came from a trusted, measured source. Only these attempts are averaged in quantitative comparisons.',
  },
];

function pct(rate) {
  return `${Math.round(rate * 100)}%`;
}

function fmtTokens(n) {
  if (typeof n !== 'number') return '—';
  return n >= 1000 ? `${(n / 1000).toFixed(1)}k` : String(Math.round(n));
}

function fmtMs(ms) {
  if (typeof ms !== 'number') return '—';
  const mins = ms / 60000;
  if (mins >= 60) return `${(mins / 60).toFixed(1)} h`;
  if (mins >= 1) return `${mins.toFixed(1)} min`;
  return `${Math.round(ms / 1000)} s`;
}

function fmtCost(c) {
  return typeof c === 'number' ? `$${c.toFixed(2)}` : '—';
}

function cellText(cell) {
  if (!cell) return '—';
  const prompts =
    typeof cell.userPrompts === 'number'
      ? cell.userPrompts === 1
        ? '1 prompt'
        : `${cell.userPrompts} prompts`
      : null;
  switch (cell.status) {
    case 'pass':
      return `✅ verified${prompts ? ` (${prompts})` : ''}`;
    case 'fail':
      return `❌ failed verify${prompts ? ` (${prompts})` : ''}`;
    case 'scored':
      return `${cell.fidelity}% fidelity${prompts ? ` (${prompts})` : ''}`;
    default:
      return `🔸 attempted, not evaluated${prompts ? ` (${prompts})` : ''}`;
  }
}

export function renderLessonsMarkdown(insights, { generatedAt } = {}) {
  const { totals, models, matrix, lessons } = insights;
  const lines = [];
  const push = (...xs) => lines.push(...xs);

  push(
    '# What can AI coding tools actually build in one shot?',
    '',
    '<!-- Generated by `node scripts/generate-lessons.mjs` — do not edit by hand. -->',
    '',
    'Every project in [`one-shots/`](one-shots/) starts from a written **vision** and is',
    'built by an AI coding tool. Each build attempt is recorded with machine-observed',
    'telemetry — which model, how many tokens, how long, how many human prompts it took —',
    'plus a human evaluation of how close the result came to the vision. This file is the',
    'digest: what the data says each model can and cannot do, regenerated from',
    '`one-shots/*/oneshot.json` after every recorded attempt.',
    ''
  );
  push(
    `_Data as of ${generatedAt || 'now'}: ${totals.oneShots} one-shot(s), ${totals.attempts} attempt(s), ` +
      `${totals.models} model(s). ${totals.benchmarkEligible} attempt(s) carry trusted (benchmark-eligible) telemetry._`,
    ''
  );

  push('## Scoreboard — one-shot × model', '');
  if (totals.attempts === 0 || models.length === 0) {
    push(
      'No attempts recorded yet. Build a one-shot with any AI coding tool, then run',
      '`node scripts/record-build.js --id <one-shot>` to add the first data point.',
      ''
    );
  } else {
    const names = models.map((m) => m.model);
    push(`| One-shot | ${names.join(' | ')} |`);
    push(`| --- | ${names.map(() => '---').join(' | ')} |`);
    for (const row of matrix) {
      push(`| \`${row.oneShotId}\` | ${names.map((n) => cellText(row.cells[n])).join(' | ')} |`);
    }
    push('');
  }

  push('## Model profiles', '');
  if (models.length === 0) {
    push('No models seen yet.', '');
  }
  for (const m of models) {
    push(`### ${m.model}`, '');
    push(`- **Attempts:** ${m.attempts} (${m.benchmarkEligibleAttempts} benchmark-eligible)`);
    push(
      `- **One-shot rate:** ${
        m.oneShotRate === null
          ? 'unknown (no prompt-count data yet)'
          : `${pct(m.oneShotRate)} (${m.oneShotCount}/${m.interactionCount} measured attempts)`
      }`
    );
    push(
      `- **Evaluations:** ${m.evaluated} — avg fidelity ${
        m.avgFidelity === null ? '—' : `${Math.round(m.avgFidelity)}%`
      }, acceptance tests ${m.verifyPasses}/${m.verifyRuns} passed`
    );
    push(
      `- **Avg build (trusted telemetry only${
        m.excludedFromAverages > 0 ? `; ${m.excludedFromAverages} attempt(s) excluded` : ''
      }):** ${fmtTokens(m.avgTokens)} tokens · ${fmtMs(m.avgDurationMs)} · ${fmtCost(m.avgCostUsd)}`
    );
    if (m.topStruggles.length > 0) {
      push(`- **Recent struggles:**`);
      for (const s of m.topStruggles) push(`  - ${s}`);
    }
    push('');
  }

  push('## Lessons learned', '');
  if (lessons.length === 0) {
    push(
      'No lessons recorded yet. After evaluating an attempt, add observations from the',
      'dashboard (Details → Evaluate → Observations) or record them with the build:',
      '`node scripts/record-build.js --id <one-shot> --lesson "..."`.',
      ''
    );
  } else {
    for (const l of lessons) {
      const date = l.timestamp ? ` (${String(l.timestamp).slice(0, 10)})` : '';
      push(`- **${l.text}** — ${l.model} on \`${l.oneShotId}\`${date}`);
    }
    push('');
  }

  push(
    '## Add your own data point',
    '',
    '1. Pick an idea (`IDEAS.md`) and promote it: `python scripts/promote.py <ID>` — or write a vision for a new folder in `one-shots/`.',
    '2. Give the ready-to-copy prompt to any AI coding tool and let it build.',
    '3. Record the attempt (telemetry is read from the tool’s own session records):',
    '   `node scripts/record-build.js --id <one-shot> --strategy single-prompt --lesson "what you learned"`',
    '4. Evaluate it in the dashboard (`cd dashboard && npm run dev`): fidelity score, acceptance test, observations.',
    '5. This file regenerates automatically — commit it with your attempt.',
    ''
  );

  push('## Glossary', '');
  for (const g of GLOSSARY) {
    push(`- **${g.term}** — ${g.def}`);
  }
  push('');

  return lines.join('\n');
}
